name: Test Docker Build

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'
    paths:
      - 'server/**'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/go-test-reusable.yml'
      - '.github/workflows/docker-build-reusable.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'server/**'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/go-test-reusable.yml'
      - '.github/workflows/docker-build-reusable.yml'

env:
  IMAGE_NAME: cobblepod-test

jobs:
  test:
    uses: ./.github/workflows/go-test-reusable.yml
    with:
      go-version: '1.24'
      working-directory: './server'

  test-build:
    needs: test
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      context: './server'
      platforms: 'linux/amd64'
      push: false
      image-name: ${{ env.IMAGE_NAME }}
      tags-input: ${{ env.IMAGE_NAME }}:test
      use-metadata: false
      login-required: false

  smoke-test:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
    - name: Test image can be created
      run: |
        docker images ${{ env.IMAGE_NAME }}:test
        echo "✅ Docker image built successfully"

    - name: Basic smoke test
      run: |
        # Test that the binary exists and can show help/version
        docker run --rm ${{ env.IMAGE_NAME }}:test ./cobblepod --help || true
        echo "✅ Basic smoke test completed"