name: Test Docker Build

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'
  pull_request:
    branches:
      - main
      - master

env:
  IMAGE_NAME: cobblepod-test

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for testing
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: ${{ env.IMAGE_NAME }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test image can be created
      run: |
        docker images ${{ env.IMAGE_NAME }}:test
        echo "✅ Docker image built successfully"

    - name: Basic smoke test
      run: |
        # Test that the binary exists and can show help/version
        docker run --rm ${{ env.IMAGE_NAME }}:test ./cobblepod --help || true
        echo "✅ Basic smoke test completed"